export * from './index/index.component';
export * from './topic/topic.component';
export * from './topic-search/topic-search.component';
export * from './topic-write/topic-write.component';
export * from './favo/favo.component';
export * from './user-msg/user-msg.component';
export * from './user-notice/user-notice.component';
export * from './user-profile/user-profile.component';
export * from './boards/boards.component';
